### PR TITLE
Plugin that displays buttons allowing visitors to either register or login and disable message form

### PR DESCRIPTION
**Pull request by gibus**
A plugin for Candy Chat to display buttons allowing visitors to either register or login and disable message form.

This is useful in the common scenario where you want to allow unregistered users to view chatrooms, without being able to write any message.

Depends on Register plugin

### CODE REVIEW

**Comment by gibus** [comment]
thx ben

**Comment by gibus** [comment]
@benlangfeld I've got some useful comments for usage, should I update the README in my forked repository and ask for another PR or should I commit and push directly in this repository?

**Comment by benlangfeld** [comment]
@gibus I just gave you write access here. Please feel free to merge changes to your plugins yourself. For changes to other plugins, please submit PRs for approval by their respective maintainers as a courtesy.

**Comment by gibus** [comment]
thx @benlangfeld still, push results in "ERROR: Permission to candy-chat/candy-plugins.git denied to gibus."

**Comment by gibus** [comment]
sorry, nevermind, I had to join the group...

**Pull request merged**
