### PR TITLE
youtu.be short links are very popular.

### PR DESCRIPTION
**Pull request by ser**
It could probably fit into single line, but I am not a javascript expert. Anyway, youtu.be links are very popular and should be added.

### CODE REVIEW

**Comment by mweibel** [comment]
Instead of an additional line you could replace
```
youtube.com\/watch\?v=
```

With

```
(youtube.com\/watch\?v=|youtu.be\/)
```

Also please have a look at the indenting, you changed the indenting :)

**Comment by Sudrien** [comment]
It could be one-lined, but the syntax is different enough it would be much harder to debug the regex.

Two suggestions:
* Force https in your iframes. There's really no reason not to take the https option these days.
* Look into preserving start time, if specified. There's an option to set it when generating a share link. I think it's t=

**Comment by Sudrien** [comment]
Thanks, mobile interface.

**Comment by mweibel** [comment]
@Sudrien: I think it's perfectly fine to use the protocol-independent `//` TBH, but it doesn't really matter (and isn't related to the PR).
Also, adding `t=` - not related to the PR, would be a welcome addition though.

**Comment by Sudrien** [comment]
As there have been no further movement - 
@ser - If you want to just fix the spacing, I'll look into `t=` support after this is merged

**Comment by ser** [comment]
I really do not understand what do you want, so I'm closing it.

**Comment by Sudrien** [comment]
@ser - Your commit converted the indentation from tabs to spaces. It's a little easier to see at https://github.com/candy-chat/candy-plugins/pull/147/files then in your text editor, probably.

**Pull request closed without merging**
